export type ModelLabelKey =
  | "deepVaR"
  | "parametricVaR"
  | "monteCarloVaR"
  | "blnnVaR"
  | "newsSentiment"
  | "lime"
  | "chat"
  | "marketData";

export interface ModelLabelConfig {
  badge: string;
  tooltip: string;
  variant?: "default" | "secondary" | "outline";
}

export const MODEL_LABELS: Record<ModelLabelKey, ModelLabelConfig> = {
  deepVaR: {
    badge: "ML estimate",
    tooltip:
      "Deep VaR from a DeepAR machine-learning model. Historical fit only; not a guarantee of future risk.",
    variant: "outline",
  },
  parametricVaR: {
    badge: "Statistical model",
    tooltip:
      "Parametric VaR assumes returns follow a statistical distribution based on historical data.",
    variant: "outline",
  },
  monteCarloVaR: {
    badge: "Statistical model",
    tooltip:
      "Monte Carlo VaR simulates many return paths from historical data. Past patterns may not repeat.",
    variant: "outline",
  },
  blnnVaR: {
    badge: "Model estimate",
    tooltip: "BLNN VaR is a model-based estimate when available.",
    variant: "outline",
  },
  newsSentiment: {
    badge: "AI sentiment",
    tooltip:
      "Sentiment scores are generated by FinBERT (AI). They may misread tone, sarcasm, or context.",
    variant: "outline",
  },
  lime: {
    badge: "AI explanation",
    tooltip:
      "LIME provides a post-hoc explanation of sentiment. It may not reflect the full model reasoning.",
    variant: "outline",
  },
  chat: {
    badge: "AI assistant",
    tooltip:
      "Generative AI assistant for educational context only. Not investment advice. May be inaccurate.",
    variant: "outline",
  },
  marketData: {
    badge: "Market data",
    tooltip:
      "Prices and headlines from third-party sources. Data may be delayed, revised, or incomplete.",
    variant: "outline",
  },
};
